query {
  info (id: "6I7OG34TofL2IM1OWBW3aK") {
    name
    nouns
    greeting
    role
    headshot {
      fields {
        file {
          url
        }
      }
    }
    skills
    university
    degree
    graduationDate
    contactMessage
    contactEmail
    contactLabel1
    contactLink1
    contactLabel2
    contactLink2
    contactLabel3
    contactLink3
  }
}
